page, skeleton, histogram
js-tasks-ru/htmlcss-20230530_scrollt pull request #4
Opened 2023-06-15 20:21 UTC by iamnewchild

2023-06-15 20:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-15 20:49 UTC, GSemikozov requested changes

2023-06-15 20:49 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__graph__item" style="height: 100px;"></div>
histogram__graph-item

2023-06-15 20:49 UTC, GSemikozov commented on components/histogram/histogram.css
> +body {
1-18 строки - либо удаляем либо уносим в normalize, поскольку это глобальные сбросы, а не сбросы на уровне компонента

2023-06-15 20:49 UTC, GSemikozov commented on components/histogram/histogram.css
> +    min-height: 50px;
лишнее, удалим

2023-06-15 20:49 UTC, GSemikozov commented on components/histogram/histogram.css
> +    margin: 0 1px;
просто margin-right

2023-06-15 20:49 UTC, GSemikozov commented on components/page/page.css
> +@import '../histogram/histogram.css';
достаточно подключать только в main

2023-06-15 20:49 UTC, GSemikozov commented on components/page/page.css
> +body {
3-19 строки - это глобальные сбросы? в блока .page можно описывать только этот блок и его его элементы и модификаторы

2023-06-15 20:49 UTC, GSemikozov commented on components/page/page.css
> +.container {
это отдельный блок

2023-06-15 20:49 UTC, GSemikozov commented on components/page/page.css
> +.container {
как и большинство описанных ниже блоков

2023-06-15 20:49 UTC, GSemikozov commented on index.html
> +            <section class="section section__cards">
блок не может быть одновременно своим элементом (как папа не может быть одновременно своим сыном)

2023-06-15 20:49 UTC, GSemikozov commented on index.html
> +                            <h3 class="card__item__title">Tooltip</h3>
.card__title

2023-06-15 20:49 UTC, GSemikozov commented on index.html
> +                <h1 class="title footer__title">About</h1>
просто footer__title

2023-06-15 21:13 UTC, iamnewchild commented on components/histogram/histogram.css
> +    min-height: 50px;
если я что-то удаляю, то у меня все исчезает (

2023-06-15 21:23 UTC, iamnewchild commented on components/page/page.css
> +.container {
мне нужно сделать каждому компонент?

2023-06-22 20:45 UTC, GSemikozov commented on components/histogram/histogram.css
> +    min-height: 50px;
если у каждого из элементов задана высота инлайном - то точно не пропадет

2023-06-22 20:46 UTC, GSemikozov commented on components/page/page.css
> +.container {
каждый блок = компонент, если он не делается в рамках задачи из задачника, складывается отдельно в папке `components`

2023-06-23 09:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-23 10:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-23 13:50 UTC, GSemikozov requested changes

2023-06-23 13:50 UTC, GSemikozov commented on components/histogram/histogram.css
> +    align-items: end;
зададим фиксированную высоту 50px, чтобы дочерним элементам инлайнить высоту в процентах

2023-06-23 13:50 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__graph-item" style="height: 100px;"></div>
см коммент ниже

2023-06-23 13:50 UTC, GSemikozov commented on components/cards/cards.css
> +.card__item {
.cards__item или все-таки .card?

2023-06-23 13:50 UTC, GSemikozov commented on components/cards/cards.css
> +.card__item {
если второе, то надо вынести как отдельный компонент

2023-06-23 13:50 UTC, GSemikozov commented on components/cards/cards.css
> +    width: 30%;
такой вариант не подойдет)
отступы договорились разрулить через флекс-контейнер и свойство gap

2023-06-23 13:50 UTC, GSemikozov commented on components/cards/cards.css
> +    padding: 80px 24px 130px 26px;
слишком большие, не соответствуют макету (должно быть `32px 25px`)

2023-06-23 13:50 UTC, GSemikozov commented on components/cards/cards.css
> +    position: absolute;
заголовок абсолютом ставить не надо

2023-06-23 13:50 UTC, GSemikozov commented on components/footer/footer.css
> +    margin-top: 71px;
марджины на уровне блока не задаем, видимо имеется в виду паддинг?

2023-06-25 12:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-25 19:28 UTC, GSemikozov approved these changes

2023-06-25 19:28 UTC, merged